package com.hanfu.payment.center.dao;

import com.hanfu.payment.center.model.HfUserCoupons;
import com.hanfu.payment.center.model.HfUserCouponsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HfUserCouponsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 20:33:43 CST 2020
     */
    long countByExample(HfUserCouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 20:33:43 CST 2020
     */
    int deleteByExample(HfUserCouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 20:33:43 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 20:33:43 CST 2020
     */
    int insert(HfUserCoupons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 20:33:43 CST 2020
     */
    int insertSelective(HfUserCoupons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 20:33:43 CST 2020
     */
    List<HfUserCoupons> selectByExample(HfUserCouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 20:33:43 CST 2020
     */
    HfUserCoupons selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 20:33:43 CST 2020
     */
    int updateByExampleSelective(@Param("record") HfUserCoupons record, @Param("example") HfUserCouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 20:33:43 CST 2020
     */
    int updateByExample(@Param("record") HfUserCoupons record, @Param("example") HfUserCouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 20:33:43 CST 2020
     */
    int updateByPrimaryKeySelective(HfUserCoupons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 20:33:43 CST 2020
     */
    int updateByPrimaryKey(HfUserCoupons record);
}