package com.hanfu.order.center.dao;

import com.hanfu.order.center.model.DiscoverPictrue;
import com.hanfu.order.center.model.DiscoverPictrueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiscoverPictrueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_pictrue
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    long countByExample(DiscoverPictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_pictrue
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int deleteByExample(DiscoverPictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_pictrue
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_pictrue
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int insert(DiscoverPictrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_pictrue
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int insertSelective(DiscoverPictrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_pictrue
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    List<DiscoverPictrue> selectByExample(DiscoverPictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_pictrue
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    DiscoverPictrue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_pictrue
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") DiscoverPictrue record, @Param("example") DiscoverPictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_pictrue
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int updateByExample(@Param("record") DiscoverPictrue record, @Param("example") DiscoverPictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_pictrue
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int updateByPrimaryKeySelective(DiscoverPictrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_pictrue
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int updateByPrimaryKey(DiscoverPictrue record);
}