package com.hanfu.order.center.dao;

import com.hanfu.order.center.model.DiscoverProduct;
import com.hanfu.order.center.model.DiscoverProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiscoverProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_product
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    long countByExample(DiscoverProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_product
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int deleteByExample(DiscoverProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_product
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_product
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int insert(DiscoverProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_product
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int insertSelective(DiscoverProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_product
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    List<DiscoverProduct> selectByExample(DiscoverProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_product
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    DiscoverProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_product
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int updateByExampleSelective(@Param("record") DiscoverProduct record, @Param("example") DiscoverProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_product
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int updateByExample(@Param("record") DiscoverProduct record, @Param("example") DiscoverProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_product
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int updateByPrimaryKeySelective(DiscoverProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discover_product
     *
     * @mbg.generated Fri Mar 20 15:54:29 CST 2020
     */
    int updateByPrimaryKey(DiscoverProduct record);
}