package com.hanfu.product.center.dao;

import com.hanfu.product.center.model.HfProductPictrue;
import com.hanfu.product.center.model.HfProductPictrueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HfProductPictrueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_product_pictrue
     *
     * @mbg.generated Sun Mar 22 17:13:44 CST 2020
     */
    long countByExample(HfProductPictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_product_pictrue
     *
     * @mbg.generated Sun Mar 22 17:13:44 CST 2020
     */
    int deleteByExample(HfProductPictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_product_pictrue
     *
     * @mbg.generated Sun Mar 22 17:13:44 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_product_pictrue
     *
     * @mbg.generated Sun Mar 22 17:13:44 CST 2020
     */
    int insert(HfProductPictrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_product_pictrue
     *
     * @mbg.generated Sun Mar 22 17:13:44 CST 2020
     */
    int insertSelective(HfProductPictrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_product_pictrue
     *
     * @mbg.generated Sun Mar 22 17:13:44 CST 2020
     */
    List<HfProductPictrue> selectByExample(HfProductPictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_product_pictrue
     *
     * @mbg.generated Sun Mar 22 17:13:44 CST 2020
     */
    HfProductPictrue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_product_pictrue
     *
     * @mbg.generated Sun Mar 22 17:13:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") HfProductPictrue record, @Param("example") HfProductPictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_product_pictrue
     *
     * @mbg.generated Sun Mar 22 17:13:44 CST 2020
     */
    int updateByExample(@Param("record") HfProductPictrue record, @Param("example") HfProductPictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_product_pictrue
     *
     * @mbg.generated Sun Mar 22 17:13:44 CST 2020
     */
    int updateByPrimaryKeySelective(HfProductPictrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_product_pictrue
     *
     * @mbg.generated Sun Mar 22 17:13:44 CST 2020
     */
    int updateByPrimaryKey(HfProductPictrue record);
}