package com.hanfu.product.center.dao;

import com.hanfu.product.center.model.ProductIntroducePictrue;
import com.hanfu.product.center.model.ProductIntroducePictrueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductIntroducePictrueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_introduce_pictrue
     *
     * @mbg.generated Mon Mar 23 16:14:03 CST 2020
     */
    long countByExample(ProductIntroducePictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_introduce_pictrue
     *
     * @mbg.generated Mon Mar 23 16:14:03 CST 2020
     */
    int deleteByExample(ProductIntroducePictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_introduce_pictrue
     *
     * @mbg.generated Mon Mar 23 16:14:03 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_introduce_pictrue
     *
     * @mbg.generated Mon Mar 23 16:14:03 CST 2020
     */
    int insert(ProductIntroducePictrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_introduce_pictrue
     *
     * @mbg.generated Mon Mar 23 16:14:03 CST 2020
     */
    int insertSelective(ProductIntroducePictrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_introduce_pictrue
     *
     * @mbg.generated Mon Mar 23 16:14:03 CST 2020
     */
    List<ProductIntroducePictrue> selectByExample(ProductIntroducePictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_introduce_pictrue
     *
     * @mbg.generated Mon Mar 23 16:14:03 CST 2020
     */
    ProductIntroducePictrue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_introduce_pictrue
     *
     * @mbg.generated Mon Mar 23 16:14:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProductIntroducePictrue record, @Param("example") ProductIntroducePictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_introduce_pictrue
     *
     * @mbg.generated Mon Mar 23 16:14:03 CST 2020
     */
    int updateByExample(@Param("record") ProductIntroducePictrue record, @Param("example") ProductIntroducePictrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_introduce_pictrue
     *
     * @mbg.generated Mon Mar 23 16:14:03 CST 2020
     */
    int updateByPrimaryKeySelective(ProductIntroducePictrue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_introduce_pictrue
     *
     * @mbg.generated Mon Mar 23 16:14:03 CST 2020
     */
    int updateByPrimaryKey(ProductIntroducePictrue record);
}