package com.hanfu.activity.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class ActivityDepartment implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_department.id
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_department.department_name
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_department.superior_id
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private Integer superiorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_department.compony_id
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private Integer componyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_department.company_name
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_department.remarks
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_department.create_time
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_department.modify_time
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private LocalDateTime modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_department.is_deleted
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private Short isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_department.file_id
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_department.id
     *
     * @return the value of activity_department.id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_department.id
     *
     * @param id the value for activity_department.id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_department.department_name
     *
     * @return the value of activity_department.department_name
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_department.department_name
     *
     * @param departmentName the value for activity_department.department_name
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_department.superior_id
     *
     * @return the value of activity_department.superior_id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public Integer getSuperiorId() {
        return superiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_department.superior_id
     *
     * @param superiorId the value for activity_department.superior_id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setSuperiorId(Integer superiorId) {
        this.superiorId = superiorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_department.compony_id
     *
     * @return the value of activity_department.compony_id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public Integer getComponyId() {
        return componyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_department.compony_id
     *
     * @param componyId the value for activity_department.compony_id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setComponyId(Integer componyId) {
        this.componyId = componyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_department.company_name
     *
     * @return the value of activity_department.company_name
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_department.company_name
     *
     * @param companyName the value for activity_department.company_name
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_department.remarks
     *
     * @return the value of activity_department.remarks
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_department.remarks
     *
     * @param remarks the value for activity_department.remarks
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_department.create_time
     *
     * @return the value of activity_department.create_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_department.create_time
     *
     * @param createTime the value for activity_department.create_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_department.modify_time
     *
     * @return the value of activity_department.modify_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_department.modify_time
     *
     * @param modifyTime the value for activity_department.modify_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_department.is_deleted
     *
     * @return the value of activity_department.is_deleted
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_department.is_deleted
     *
     * @param isDeleted the value for activity_department.is_deleted
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_department.file_id
     *
     * @return the value of activity_department.file_id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_department.file_id
     *
     * @param fileId the value for activity_department.file_id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", departmentName=").append(departmentName);
        sb.append(", superiorId=").append(superiorId);
        sb.append(", componyId=").append(componyId);
        sb.append(", companyName=").append(companyName);
        sb.append(", remarks=").append(remarks);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", fileId=").append(fileId);
        sb.append("]");
        return sb.toString();
    }
}