package com.hanfu.activity.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class ActivityUserExperience implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.id
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.user_id
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.company_name
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.department_name
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private String departmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.company_post
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private String companyPost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.job_content
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private String jobContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.achievements
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private String achievements;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.start_time
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private LocalDateTime startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.end_time
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private LocalDateTime endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.remarks
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.create_time
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.modify_time
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private LocalDateTime modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_user_experience.is_deleted
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private Short isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table activity_user_experience
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.id
     *
     * @return the value of activity_user_experience.id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.id
     *
     * @param id the value for activity_user_experience.id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.user_id
     *
     * @return the value of activity_user_experience.user_id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.user_id
     *
     * @param userId the value for activity_user_experience.user_id
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.company_name
     *
     * @return the value of activity_user_experience.company_name
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.company_name
     *
     * @param companyName the value for activity_user_experience.company_name
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.department_name
     *
     * @return the value of activity_user_experience.department_name
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.department_name
     *
     * @param departmentName the value for activity_user_experience.department_name
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName == null ? null : departmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.company_post
     *
     * @return the value of activity_user_experience.company_post
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public String getCompanyPost() {
        return companyPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.company_post
     *
     * @param companyPost the value for activity_user_experience.company_post
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setCompanyPost(String companyPost) {
        this.companyPost = companyPost == null ? null : companyPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.job_content
     *
     * @return the value of activity_user_experience.job_content
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public String getJobContent() {
        return jobContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.job_content
     *
     * @param jobContent the value for activity_user_experience.job_content
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setJobContent(String jobContent) {
        this.jobContent = jobContent == null ? null : jobContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.achievements
     *
     * @return the value of activity_user_experience.achievements
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public String getAchievements() {
        return achievements;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.achievements
     *
     * @param achievements the value for activity_user_experience.achievements
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setAchievements(String achievements) {
        this.achievements = achievements == null ? null : achievements.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.start_time
     *
     * @return the value of activity_user_experience.start_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public LocalDateTime getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.start_time
     *
     * @param startTime the value for activity_user_experience.start_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.end_time
     *
     * @return the value of activity_user_experience.end_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.end_time
     *
     * @param endTime the value for activity_user_experience.end_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.remarks
     *
     * @return the value of activity_user_experience.remarks
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.remarks
     *
     * @param remarks the value for activity_user_experience.remarks
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.create_time
     *
     * @return the value of activity_user_experience.create_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.create_time
     *
     * @param createTime the value for activity_user_experience.create_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.modify_time
     *
     * @return the value of activity_user_experience.modify_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.modify_time
     *
     * @param modifyTime the value for activity_user_experience.modify_time
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_user_experience.is_deleted
     *
     * @return the value of activity_user_experience.is_deleted
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_user_experience.is_deleted
     *
     * @param isDeleted the value for activity_user_experience.is_deleted
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_user_experience
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", companyName=").append(companyName);
        sb.append(", departmentName=").append(departmentName);
        sb.append(", companyPost=").append(companyPost);
        sb.append(", jobContent=").append(jobContent);
        sb.append(", achievements=").append(achievements);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", remarks=").append(remarks);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}