package com.hanfu.product.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class cancelProduct implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cancel_product.id
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cancel_product.cancel_id
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    private Integer cancelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cancel_product.claim
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    private Short claim;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cancel_product.product_id
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cancel_product.is_deleted
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    private Short isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cancel_product.create_time
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cancel_product.modify_time
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cancel_product
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cancel_product.id
     *
     * @return the value of cancel_product.id
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cancel_product.id
     *
     * @param id the value for cancel_product.id
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cancel_product.cancel_id
     *
     * @return the value of cancel_product.cancel_id
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public Integer getCancelId() {
        return cancelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cancel_product.cancel_id
     *
     * @param cancelId the value for cancel_product.cancel_id
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public void setCancelId(Integer cancelId) {
        this.cancelId = cancelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cancel_product.claim
     *
     * @return the value of cancel_product.claim
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public Short getClaim() {
        return claim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cancel_product.claim
     *
     * @param claim the value for cancel_product.claim
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public void setClaim(Short claim) {
        this.claim = claim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cancel_product.product_id
     *
     * @return the value of cancel_product.product_id
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cancel_product.product_id
     *
     * @param productId the value for cancel_product.product_id
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cancel_product.is_deleted
     *
     * @return the value of cancel_product.is_deleted
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cancel_product.is_deleted
     *
     * @param isDeleted the value for cancel_product.is_deleted
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cancel_product.create_time
     *
     * @return the value of cancel_product.create_time
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cancel_product.create_time
     *
     * @param createTime the value for cancel_product.create_time
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cancel_product.modify_time
     *
     * @return the value of cancel_product.modify_time
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cancel_product.modify_time
     *
     * @param modifyTime the value for cancel_product.modify_time
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cancel_product
     *
     * @mbg.generated Sat Mar 21 16:17:41 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cancelId=").append(cancelId);
        sb.append(", claim=").append(claim);
        sb.append(", productId=").append(productId);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append("]");
        return sb.toString();
    }
}