package com.hanfu.payment.center.manual.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class HfUserCoupons implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.id
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.user_id
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.hf_name
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private String hfName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.hf_desc
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private String hfDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.hf_status
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private String hfStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.coupons_type
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private String couponsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.coupons_info
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private String couponsInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.coupons_strategy_id
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private Integer couponsStrategyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.effective_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private LocalDateTime effectiveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.expire_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private LocalDateTime expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.create_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private LocalDateTime createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.modify_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private LocalDateTime modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_user_coupons.id_deleted
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private Byte idDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.id
     *
     * @return the value of hf_user_coupons.id
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.id
     *
     * @param id the value for hf_user_coupons.id
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.user_id
     *
     * @return the value of hf_user_coupons.user_id
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.user_id
     *
     * @param userId the value for hf_user_coupons.user_id
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.hf_name
     *
     * @return the value of hf_user_coupons.hf_name
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public String getHfName() {
        return hfName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.hf_name
     *
     * @param hfName the value for hf_user_coupons.hf_name
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setHfName(String hfName) {
        this.hfName = hfName == null ? null : hfName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.hf_desc
     *
     * @return the value of hf_user_coupons.hf_desc
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public String getHfDesc() {
        return hfDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.hf_desc
     *
     * @param hfDesc the value for hf_user_coupons.hf_desc
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setHfDesc(String hfDesc) {
        this.hfDesc = hfDesc == null ? null : hfDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.hf_status
     *
     * @return the value of hf_user_coupons.hf_status
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public String getHfStatus() {
        return hfStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.hf_status
     *
     * @param hfStatus the value for hf_user_coupons.hf_status
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setHfStatus(String hfStatus) {
        this.hfStatus = hfStatus == null ? null : hfStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.coupons_type
     *
     * @return the value of hf_user_coupons.coupons_type
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public String getCouponsType() {
        return couponsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.coupons_type
     *
     * @param couponsType the value for hf_user_coupons.coupons_type
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setCouponsType(String couponsType) {
        this.couponsType = couponsType == null ? null : couponsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.coupons_info
     *
     * @return the value of hf_user_coupons.coupons_info
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public String getCouponsInfo() {
        return couponsInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.coupons_info
     *
     * @param couponsInfo the value for hf_user_coupons.coupons_info
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setCouponsInfo(String couponsInfo) {
        this.couponsInfo = couponsInfo == null ? null : couponsInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.coupons_strategy_id
     *
     * @return the value of hf_user_coupons.coupons_strategy_id
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public Integer getCouponsStrategyId() {
        return couponsStrategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.coupons_strategy_id
     *
     * @param couponsStrategyId the value for hf_user_coupons.coupons_strategy_id
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setCouponsStrategyId(Integer couponsStrategyId) {
        this.couponsStrategyId = couponsStrategyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.effective_date
     *
     * @return the value of hf_user_coupons.effective_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public LocalDateTime getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.effective_date
     *
     * @param effectiveDate the value for hf_user_coupons.effective_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setEffectiveDate(LocalDateTime effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.expire_date
     *
     * @return the value of hf_user_coupons.expire_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public LocalDateTime getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.expire_date
     *
     * @param expireDate the value for hf_user_coupons.expire_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setExpireDate(LocalDateTime expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.create_date
     *
     * @return the value of hf_user_coupons.create_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.create_date
     *
     * @param createDate the value for hf_user_coupons.create_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.modify_date
     *
     * @return the value of hf_user_coupons.modify_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public LocalDateTime getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.modify_date
     *
     * @param modifyDate the value for hf_user_coupons.modify_date
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setModifyDate(LocalDateTime modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_user_coupons.id_deleted
     *
     * @return the value of hf_user_coupons.id_deleted
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public Byte getIdDeleted() {
        return idDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_user_coupons.id_deleted
     *
     * @param idDeleted the value for hf_user_coupons.id_deleted
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    public void setIdDeleted(Byte idDeleted) {
        this.idDeleted = idDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hf_user_coupons
     *
     * @mbg.generated Mon Feb 10 08:20:35 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", hfName=").append(hfName);
        sb.append(", hfDesc=").append(hfDesc);
        sb.append(", hfStatus=").append(hfStatus);
        sb.append(", couponsType=").append(couponsType);
        sb.append(", couponsInfo=").append(couponsInfo);
        sb.append(", couponsStrategyId=").append(couponsStrategyId);
        sb.append(", effectiveDate=").append(effectiveDate);
        sb.append(", expireDate=").append(expireDate);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", idDeleted=").append(idDeleted);
        sb.append("]");
        return sb.toString();
    }
}