package com.hanfu.user.center.dao;

import com.hanfu.user.center.model.JurisdictionModule;
import com.hanfu.user.center.model.JurisdictionModuleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JurisdictionModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction_module
     *
     * @mbg.generated Tue Jan 07 14:58:38 CST 2020
     */
    long countByExample(JurisdictionModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction_module
     *
     * @mbg.generated Tue Jan 07 14:58:38 CST 2020
     */
    int deleteByExample(JurisdictionModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction_module
     *
     * @mbg.generated Tue Jan 07 14:58:38 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction_module
     *
     * @mbg.generated Tue Jan 07 14:58:38 CST 2020
     */
    int insert(JurisdictionModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction_module
     *
     * @mbg.generated Tue Jan 07 14:58:38 CST 2020
     */
    int insertSelective(JurisdictionModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction_module
     *
     * @mbg.generated Tue Jan 07 14:58:38 CST 2020
     */
    List<JurisdictionModule> selectByExample(JurisdictionModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction_module
     *
     * @mbg.generated Tue Jan 07 14:58:38 CST 2020
     */
    JurisdictionModule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction_module
     *
     * @mbg.generated Tue Jan 07 14:58:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") JurisdictionModule record, @Param("example") JurisdictionModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction_module
     *
     * @mbg.generated Tue Jan 07 14:58:38 CST 2020
     */
    int updateByExample(@Param("record") JurisdictionModule record, @Param("example") JurisdictionModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction_module
     *
     * @mbg.generated Tue Jan 07 14:58:38 CST 2020
     */
    int updateByPrimaryKeySelective(JurisdictionModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction_module
     *
     * @mbg.generated Tue Jan 07 14:58:38 CST 2020
     */
    int updateByPrimaryKey(JurisdictionModule record);
}