package com.hanfu.activity.center.dao;

import com.hanfu.activity.center.model.ActivityEvaluateTemplate;
import com.hanfu.activity.center.model.ActivityEvaluateTemplateExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ActivityEvaluateTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_evaluate_template
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    long countByExample(ActivityEvaluateTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_evaluate_template
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int deleteByExample(ActivityEvaluateTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_evaluate_template
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_evaluate_template
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int insert(ActivityEvaluateTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_evaluate_template
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int insertSelective(ActivityEvaluateTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_evaluate_template
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    List<ActivityEvaluateTemplate> selectByExample(ActivityEvaluateTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_evaluate_template
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    ActivityEvaluateTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_evaluate_template
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActivityEvaluateTemplate record, @Param("example") ActivityEvaluateTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_evaluate_template
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int updateByExample(@Param("record") ActivityEvaluateTemplate record, @Param("example") ActivityEvaluateTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_evaluate_template
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int updateByPrimaryKeySelective(ActivityEvaluateTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_evaluate_template
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int updateByPrimaryKey(ActivityEvaluateTemplate record);
}