package com.hanfu.activity.center.dao;

import com.hanfu.activity.center.model.ActivityDepartment;
import com.hanfu.activity.center.model.ActivityDepartmentExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ActivityDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    long countByExample(ActivityDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int deleteByExample(ActivityDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int insert(ActivityDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int insertSelective(ActivityDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    List<ActivityDepartment> selectByExample(ActivityDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    ActivityDepartment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActivityDepartment record, @Param("example") ActivityDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int updateByExample(@Param("record") ActivityDepartment record, @Param("example") ActivityDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int updateByPrimaryKeySelective(ActivityDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activity_department
     *
     * @mbg.generated Tue Dec 03 07:29:15 CST 2019
     */
    int updateByPrimaryKey(ActivityDepartment record);
}