package com.hanfu.user.center.model;

import java.io.Serializable;

public class Admin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.department
     *
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.email
     *
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.encodedPassword
     *
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    private String encodedpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.name
     *
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.username
     *
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.department
     *
     * @return the value of admin.department
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.department
     *
     * @param department the value for admin.department
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.email
     *
     * @return the value of admin.email
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.email
     *
     * @param email the value for admin.email
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.encodedPassword
     *
     * @return the value of admin.encodedPassword
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    public String getEncodedpassword() {
        return encodedpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.encodedPassword
     *
     * @param encodedpassword the value for admin.encodedPassword
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    public void setEncodedpassword(String encodedpassword) {
        this.encodedpassword = encodedpassword == null ? null : encodedpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.name
     *
     * @return the value of admin.name
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.name
     *
     * @param name the value for admin.name
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Mon Sep 23 14:30:21 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", department=").append(department);
        sb.append(", email=").append(email);
        sb.append(", encodedpassword=").append(encodedpassword);
        sb.append(", name=").append(name);
        sb.append(", username=").append(username);
        sb.append("]");
        return sb.toString();
    }
}