package com.hanfu.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Jurisdiction implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.id
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.jurisdiction_name
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    private String jurisdictionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.jurisdiction_module
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    private String jurisdictionModule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.parent_inventory_id
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    private String parentInventoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.inventory_status
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    private Short inventoryStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.inventory_rank_id
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    private Integer inventoryRankId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.access_code
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    private String accessCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.create_time
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.modify_time
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jurisdiction.is_deleted
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    private Short isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.id
     *
     * @return the value of jurisdiction.id
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.id
     *
     * @param id the value for jurisdiction.id
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.jurisdiction_name
     *
     * @return the value of jurisdiction.jurisdiction_name
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public String getJurisdictionName() {
        return jurisdictionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.jurisdiction_name
     *
     * @param jurisdictionName the value for jurisdiction.jurisdiction_name
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setJurisdictionName(String jurisdictionName) {
        this.jurisdictionName = jurisdictionName == null ? null : jurisdictionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.jurisdiction_module
     *
     * @return the value of jurisdiction.jurisdiction_module
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public String getJurisdictionModule() {
        return jurisdictionModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.jurisdiction_module
     *
     * @param jurisdictionModule the value for jurisdiction.jurisdiction_module
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setJurisdictionModule(String jurisdictionModule) {
        this.jurisdictionModule = jurisdictionModule == null ? null : jurisdictionModule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.parent_inventory_id
     *
     * @return the value of jurisdiction.parent_inventory_id
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public String getParentInventoryId() {
        return parentInventoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.parent_inventory_id
     *
     * @param parentInventoryId the value for jurisdiction.parent_inventory_id
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setParentInventoryId(String parentInventoryId) {
        this.parentInventoryId = parentInventoryId == null ? null : parentInventoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.inventory_status
     *
     * @return the value of jurisdiction.inventory_status
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public Short getInventoryStatus() {
        return inventoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.inventory_status
     *
     * @param inventoryStatus the value for jurisdiction.inventory_status
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setInventoryStatus(Short inventoryStatus) {
        this.inventoryStatus = inventoryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.inventory_rank_id
     *
     * @return the value of jurisdiction.inventory_rank_id
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public Integer getInventoryRankId() {
        return inventoryRankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.inventory_rank_id
     *
     * @param inventoryRankId the value for jurisdiction.inventory_rank_id
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setInventoryRankId(Integer inventoryRankId) {
        this.inventoryRankId = inventoryRankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.access_code
     *
     * @return the value of jurisdiction.access_code
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public String getAccessCode() {
        return accessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.access_code
     *
     * @param accessCode the value for jurisdiction.access_code
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setAccessCode(String accessCode) {
        this.accessCode = accessCode == null ? null : accessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.create_time
     *
     * @return the value of jurisdiction.create_time
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.create_time
     *
     * @param createTime the value for jurisdiction.create_time
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.modify_time
     *
     * @return the value of jurisdiction.modify_time
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.modify_time
     *
     * @param modifyTime the value for jurisdiction.modify_time
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jurisdiction.is_deleted
     *
     * @return the value of jurisdiction.is_deleted
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public Short getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jurisdiction.is_deleted
     *
     * @param isDeleted the value for jurisdiction.is_deleted
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setIsDeleted(Short isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", jurisdictionName=").append(jurisdictionName);
        sb.append(", jurisdictionModule=").append(jurisdictionModule);
        sb.append(", parentInventoryId=").append(parentInventoryId);
        sb.append(", inventoryStatus=").append(inventoryStatus);
        sb.append(", inventoryRankId=").append(inventoryRankId);
        sb.append(", accessCode=").append(accessCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}