package com.hanfu.user.center.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class JurisdictionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public JurisdictionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameIsNull() {
            addCriterion("jurisdiction_name is null");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameIsNotNull() {
            addCriterion("jurisdiction_name is not null");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameEqualTo(String value) {
            addCriterion("jurisdiction_name =", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameNotEqualTo(String value) {
            addCriterion("jurisdiction_name <>", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameGreaterThan(String value) {
            addCriterion("jurisdiction_name >", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameGreaterThanOrEqualTo(String value) {
            addCriterion("jurisdiction_name >=", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameLessThan(String value) {
            addCriterion("jurisdiction_name <", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameLessThanOrEqualTo(String value) {
            addCriterion("jurisdiction_name <=", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameLike(String value) {
            addCriterion("jurisdiction_name like", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameNotLike(String value) {
            addCriterion("jurisdiction_name not like", value, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameIn(List<String> values) {
            addCriterion("jurisdiction_name in", values, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameNotIn(List<String> values) {
            addCriterion("jurisdiction_name not in", values, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameBetween(String value1, String value2) {
            addCriterion("jurisdiction_name between", value1, value2, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionNameNotBetween(String value1, String value2) {
            addCriterion("jurisdiction_name not between", value1, value2, "jurisdictionName");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleIsNull() {
            addCriterion("jurisdiction_module is null");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleIsNotNull() {
            addCriterion("jurisdiction_module is not null");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleEqualTo(String value) {
            addCriterion("jurisdiction_module =", value, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleNotEqualTo(String value) {
            addCriterion("jurisdiction_module <>", value, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleGreaterThan(String value) {
            addCriterion("jurisdiction_module >", value, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleGreaterThanOrEqualTo(String value) {
            addCriterion("jurisdiction_module >=", value, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleLessThan(String value) {
            addCriterion("jurisdiction_module <", value, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleLessThanOrEqualTo(String value) {
            addCriterion("jurisdiction_module <=", value, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleLike(String value) {
            addCriterion("jurisdiction_module like", value, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleNotLike(String value) {
            addCriterion("jurisdiction_module not like", value, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleIn(List<String> values) {
            addCriterion("jurisdiction_module in", values, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleNotIn(List<String> values) {
            addCriterion("jurisdiction_module not in", values, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleBetween(String value1, String value2) {
            addCriterion("jurisdiction_module between", value1, value2, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andJurisdictionModuleNotBetween(String value1, String value2) {
            addCriterion("jurisdiction_module not between", value1, value2, "jurisdictionModule");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdIsNull() {
            addCriterion("parent_inventory_id is null");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdIsNotNull() {
            addCriterion("parent_inventory_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdEqualTo(String value) {
            addCriterion("parent_inventory_id =", value, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdNotEqualTo(String value) {
            addCriterion("parent_inventory_id <>", value, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdGreaterThan(String value) {
            addCriterion("parent_inventory_id >", value, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdGreaterThanOrEqualTo(String value) {
            addCriterion("parent_inventory_id >=", value, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdLessThan(String value) {
            addCriterion("parent_inventory_id <", value, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdLessThanOrEqualTo(String value) {
            addCriterion("parent_inventory_id <=", value, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdLike(String value) {
            addCriterion("parent_inventory_id like", value, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdNotLike(String value) {
            addCriterion("parent_inventory_id not like", value, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdIn(List<String> values) {
            addCriterion("parent_inventory_id in", values, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdNotIn(List<String> values) {
            addCriterion("parent_inventory_id not in", values, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdBetween(String value1, String value2) {
            addCriterion("parent_inventory_id between", value1, value2, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andParentInventoryIdNotBetween(String value1, String value2) {
            addCriterion("parent_inventory_id not between", value1, value2, "parentInventoryId");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusIsNull() {
            addCriterion("inventory_status is null");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusIsNotNull() {
            addCriterion("inventory_status is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusEqualTo(Short value) {
            addCriterion("inventory_status =", value, "inventoryStatus");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusNotEqualTo(Short value) {
            addCriterion("inventory_status <>", value, "inventoryStatus");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusGreaterThan(Short value) {
            addCriterion("inventory_status >", value, "inventoryStatus");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("inventory_status >=", value, "inventoryStatus");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusLessThan(Short value) {
            addCriterion("inventory_status <", value, "inventoryStatus");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusLessThanOrEqualTo(Short value) {
            addCriterion("inventory_status <=", value, "inventoryStatus");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusIn(List<Short> values) {
            addCriterion("inventory_status in", values, "inventoryStatus");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusNotIn(List<Short> values) {
            addCriterion("inventory_status not in", values, "inventoryStatus");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusBetween(Short value1, Short value2) {
            addCriterion("inventory_status between", value1, value2, "inventoryStatus");
            return (Criteria) this;
        }

        public Criteria andInventoryStatusNotBetween(Short value1, Short value2) {
            addCriterion("inventory_status not between", value1, value2, "inventoryStatus");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdIsNull() {
            addCriterion("inventory_rank_id is null");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdIsNotNull() {
            addCriterion("inventory_rank_id is not null");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdEqualTo(Integer value) {
            addCriterion("inventory_rank_id =", value, "inventoryRankId");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdNotEqualTo(Integer value) {
            addCriterion("inventory_rank_id <>", value, "inventoryRankId");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdGreaterThan(Integer value) {
            addCriterion("inventory_rank_id >", value, "inventoryRankId");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("inventory_rank_id >=", value, "inventoryRankId");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdLessThan(Integer value) {
            addCriterion("inventory_rank_id <", value, "inventoryRankId");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdLessThanOrEqualTo(Integer value) {
            addCriterion("inventory_rank_id <=", value, "inventoryRankId");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdIn(List<Integer> values) {
            addCriterion("inventory_rank_id in", values, "inventoryRankId");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdNotIn(List<Integer> values) {
            addCriterion("inventory_rank_id not in", values, "inventoryRankId");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdBetween(Integer value1, Integer value2) {
            addCriterion("inventory_rank_id between", value1, value2, "inventoryRankId");
            return (Criteria) this;
        }

        public Criteria andInventoryRankIdNotBetween(Integer value1, Integer value2) {
            addCriterion("inventory_rank_id not between", value1, value2, "inventoryRankId");
            return (Criteria) this;
        }

        public Criteria andAccessCodeIsNull() {
            addCriterion("access_code is null");
            return (Criteria) this;
        }

        public Criteria andAccessCodeIsNotNull() {
            addCriterion("access_code is not null");
            return (Criteria) this;
        }

        public Criteria andAccessCodeEqualTo(String value) {
            addCriterion("access_code =", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeNotEqualTo(String value) {
            addCriterion("access_code <>", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeGreaterThan(String value) {
            addCriterion("access_code >", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeGreaterThanOrEqualTo(String value) {
            addCriterion("access_code >=", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeLessThan(String value) {
            addCriterion("access_code <", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeLessThanOrEqualTo(String value) {
            addCriterion("access_code <=", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeLike(String value) {
            addCriterion("access_code like", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeNotLike(String value) {
            addCriterion("access_code not like", value, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeIn(List<String> values) {
            addCriterion("access_code in", values, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeNotIn(List<String> values) {
            addCriterion("access_code not in", values, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeBetween(String value1, String value2) {
            addCriterion("access_code between", value1, value2, "accessCode");
            return (Criteria) this;
        }

        public Criteria andAccessCodeNotBetween(String value1, String value2) {
            addCriterion("access_code not between", value1, value2, "accessCode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(LocalDateTime value) {
            addCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(LocalDateTime value) {
            addCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(LocalDateTime value) {
            addCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(LocalDateTime value) {
            addCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<LocalDateTime> values) {
            addCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<LocalDateTime> values) {
            addCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Short value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Short value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Short value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Short value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Short value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Short value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Short> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Short> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Short value1, Short value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Short value1, Short value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jurisdiction
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 17 14:56:16 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jurisdiction
     *
     * @mbg.generated Tue Mar 17 14:56:16 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}